### ISSUE TITLE
Blockquotes indentation produces error if no content

### ISSUE THREAD

**Issue by leipert** [wooorm/mdast-lint#19]
While using https://atom.io/packages/linter-markdown:

Started typing a block quote:

```
>
```

This error was produced:

```
TypeError: Cannot read property 'children' of undefined
  at toString (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/node_modules/mdast-util-to-string/index.js:33:14)
  at check (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/rules/blockquote-indentation.js:49:19)
  at /Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/rules/blockquote-indentation.js:97:25
  at one (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/node_modules/mdast-util-visit/index.js:96:22)
  at /Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/node_modules/mdast-util-visit/index.js:83:29
  at forwards (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/node_modules/mdast-util-visit/index.js:24:13)
  at all (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/node_modules/mdast-util-visit/index.js:82:16)
  at one (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/node_modules/mdast-util-visit/index.js:100:20)
  at visit (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/node_modules/mdast-util-visit/index.js:106:5)
  at blockquoteIndentation (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/rules/blockquote-indentation.js:73:5)
  at Of.plugin (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/index.js:89:13)
  at Of.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
  at next (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
  at /Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:121:18
  at done (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/index.js:82:17)
  at noMissingBlankLines (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/rules/no-missing-blank-lines.js:74:5)
  at Of.plugin (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/index.js:89:13)
  at Of.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
  at next (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
  at /Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:121:18
  at done (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/index.js:82:17)
  at noConsecutiveBlankLines (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/rules/no-consecutive-blank-lines.js:121:5)
  at Of.plugin (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/index.js:89:13)
  at Of.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
  at next (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
  at /Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:121:18
  at done (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/index.js:82:17)
  at noLiteralURLs (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/rules/no-literal-urls.js:55:5)
  at Of.plugin (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/index.js:89:13)
  at Of.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
  at next (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
  at /Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:121:18
  at done (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/index.js:82:17)
  at noAutoLinkWithoutProtocol (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/rules/no-auto-link-without-protocol.js:77:5)
  at Of.plugin (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast-lint/lib/index.js:89:13)
  at Of.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
  at next (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
  at /Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:121:18
  at Of.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:83:42)
  at Of.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:57:27)
  at next (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
  at /Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:121:18
  at Of.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:83:42)
  at Of.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:57:27)
  at next (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
  at Of.Ware.run (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/lib/index.js:88:3)
  at Processor.run (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/unified/index.js:149:23)
  at Ware.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/unified/index.js:30:21)
  at Ware.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
  at next (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
  at /Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:121:18
  at Ware.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:83:42)
  at Ware.<anonymous> (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:57:27)
  at next (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
  at Ware.run (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/ware/lib/index.js:88:3)
  at Processor.process (/Users/leipert/.atom/packages/linter-markdown/node_modules/mdast/node_modules/unified/index.js:243:18)
  at module.exports._Class.lint (/Users/leipert/.atom/packages/linter-markdown/lib/linter.coffee:56:19)
  at _Class.module.exports._Class.lint (/Users/leipert/.atom/packages/linter-markdown/lib/linter.coffee:55:11)
  at _Class.__bind [as lint] (/Users/leipert/.atom/packages/linter-markdown/lib/linter.coffee:1:1)
  at LinterRegistry.triggerLinter.Promise.then._this.emitter.emit.linter (/Users/leipert/.atom/packages/linter/lib/linter-registry.coffee:55:22)
  at LinterRegistry.triggerLinter (/Users/leipert/.atom/packages/linter/lib/linter-registry.coffee:54:16)
  at /Users/leipert/.atom/packages/linter/lib/linter-registry.coffee:48:17
  at Array.map (native)
  at /Users/leipert/.atom/packages/linter/lib/linter-registry.coffee:46:27
  at process._tickCallback (node.js:367:9)
```

**Comment by zcei** [comment]
Haha I saw the mails and thought: "A small one I can fix right away, haven't contributed more so far.."

> @wooorm closed this issue from a commit 1 minute ago" :+1:

**Comment by wooorm** [comment]
Ha sorry, I’m too fast 😉
Let’s try this linter out! Looks like great work @leipert!
